### ISSUE TITLE
More compile errors

### ISSUE THREAD

**Issue by Zetari** [NovaMods/nova-renderer#101]
Followed all of the install directions, might just be me being an idiot and missing something, but I get an error when running `.\gradlew build buildDll`.
[Log](https://hastebin.com/oyeqamined.tex)
I don't want to do anything without proper instruction because I'm not really experienced in compiling and building things
I might just be forgetting to do something, but I've tried other error checks like [#85](https://github.com/NovaMods/nova-renderer/issues/85), [#89](https://github.com/NovaMods/nova-renderer/issues/89), [#92](https://github.com/NovaMods/nova-renderer/issues/92), and a few others, as well as trying the patch thing, but I have yet to find a fix. Maybe there isn't one, I don't know, but I've been watching this repository for a while and it's just a few days ago I decided to try it.

**Comment by DethRaid** [comment]
Looks like MCP didn't properly set up. Did you run `.\gradlew setup` before doing anything?

**Comment by Zetari** [comment]
Yes, I did. 
I'm going to do a complete clean setup again, up until the unpassable error. All logs will be posted below.
[Git Clone](https://hastebin.com/hiyisizaqu.erl)
[Gradlew Setup](https://hastebin.com/ayinamusam.cs)
[Gradlew Build BuildDll](https://hastebin.com/xifuyavuyi.tex)

**Comment by Zetari** [comment]
Also, did you mean to use `.\gradlew setup` before I did the Clone? I'm just following the directions on the install page of the repository.

**Comment by DethRaid** [comment]
No, you definitely need to do it after clone and before build

**Comment by DethRaid** [comment]
Looks like the thing happened to you that happens to everyone: the patch file failed to apply. The recommended fix is to wait for us to develop forge support, which will let us distribute pre built binaries and avoid issues like this

**Comment by Zetari** [comment]
Alright, thanks :p

**Comment by DethRaid** [comment]
We're just committed some changes to the build script. Could you test again and see if Nova works for you?

**Comment by DethRaid** [comment]
@Zetari Does the new build script work for you?

**Comment by DethRaid** [comment]
Closing this issue due to lack of response
