### ISSUE TITLE
Vulkan runs out of memory

### ISSUE THREAD

**Issue by Rayzr522** [NovaMods/nova-renderer#118]
So, miraculously I have finally managed to get the `vulkan` branch of nova to setup, build, and compile on my computer. Hooray!

... except for one little problem; I can't get it to run :P

Every time I try to run nova, it compiles, outputs some default Minecraft log stuffs, then spews out a bunch of Vulkan errors before printing a Vulkan error about running out of memory and crashing. It should probably be noted that right before saying it runs out of memory, my computer locks up a little. 

Attached is a log file with all the output from `./gradlew runNova`. If you need anything else, just let me know!

[nova-error.log](https://github.com/NovaMods/nova-renderer/files/1856582/nova-error.log)

*P.S.* - keep up the good work, I can't wait to see this project get to the point that everyone can use it :D

**Comment by DethRaid** [comment]
What operating system are you on? What GPU do you have and how much RAM and vram do you have?

**Comment by Rayzr522** [comment]
Wow, didn't expect such a fast response, sorry to keep you waiting.

**OS:** Arch Linux, running Linux kernel version 4.15.9-1-ARCH
**GPU:** NVIDIA GeForce GTX 980 Ti
**VRAM:** 6GB GDDR5

**Comment by DethRaid** [comment]
Hmm... that's kind of a weird error. The error is saying that I didn't make the descriptor set pool big enough, but I've been running this code locally without any trouble. Maybe the driver for the 980 Ti works a little differently than the one for the 1080? 

I see a few other errors in that log that I've fixed in the last few hours. Could you try pulling the latest and seeing if that works for you? If not I'll do some deeper debugging

**Comment by Rayzr522** [comment]
Good news(ish)! It didn't crash. Bad news? Well, it almost froze my system and it was just a black screen :P

Exact steps:

```bash
$ cd ~/GitHub/nova-renderer
$ git pull
[it got your changes]
$ cd ~/.local/lib/VulkanSDK/1.0.65.0
$ source setup-env.sh
$ cd -
$ ./gradlew build
$ rm -rf ~/Desktop/nova-output.log && ./gradlew runNova &> ~/Desktop/nova-output.log
```

That's essentially everything I did.

No more out of memory errors, but it almost locked up my DE. Here's the output: 
[nova-output.log](https://github.com/NovaMods/nova-renderer/files/1860210/nova-output.log)

I see a few errors in there still, but I'm gonna go try it on another DE just to see if it's possibly my setup rather than your code.

**Comment by DethRaid** [comment]
I've also had problems where Nova locks up at this point. Pretty sure the error is `ERROR: API: DS Queue 0x0x7f0c2c7d8710 is waiting on semaphore 0x36 that has no way to be signaled.` (at least, that's _a_ error). I'm actually working on reworking the renderer internals, but I'll try to fix that issue while I'm at it

**Comment by Rayzr522** [comment]
Alright, sounds good. Just let me know if there’s any information you need or anything you want me to test :)

**Comment by Rayzr522** [comment]
Resolved at some point.
