### ISSUE TITLE
The Discord Server's Invite Is Not Working

### ISSUE THREAD

**Issue by ToastedToast128** [NovaMods/nova-renderer#133]
[https://discordapp.com/invite/014ux6siiDogn9FLz](url) is not a valid invite anymore.

**Comment by DethRaid** [comment]
It seems to be working fine for me...

The link in your issue takes me to `https://github.com/NovaMods/nova-renderer/issues/url`, which is as you say not a valid URL. However, `https://discordapp.com/invite/014ux6siiDogn9FLz` is the correct URL, and that URL worked fine when I just tried it

**Comment by ToastedToast128** [comment]
i connected through the discord client, nevermind

**Comment by ToastedToast128** [comment]
[](url)
