### ISSUE TITLE
Crash with Nova Alpha 0.7.0 {Pre-Alpha}

### ISSUE THREAD

**Issue by Coolbro458** [NovaMods/nova-renderer#138]
Running Forge 2655 and still having issues. Crash Log Provided.
[latest.log](https://github.com/NovaMods/nova-renderer/files/2204450/latest.log)

**Comment by Coolbro458** [comment]
[latest.log](https://github.com/NovaMods/nova-renderer/files/2204443/latest.log)

**Comment by McHox** [comment]
fix

**Comment by Eddi2015** [comment]
Please try to upgrade forge to the latest version. Should be .2738 atm

**Comment by ImperatorS79** [comment]
Which vulkan version nova required ?

**Comment by DethRaid** [comment]
Try release 0.7.3

**Comment by Eddi2015** [comment]
0.7.3 is working, but has some GUI issues. e.g. I can't click on some buttons etc.

**Comment by DethRaid** [comment]
You usually have to click on things a lot of times before your click registers.

Since 0.7.3 is not crashing for you, I'm going to close this issue
