### ISSUE TITLE
Crash Nova 0.7.1

### ISSUE THREAD

**Issue by Eddi2015** [NovaMods/nova-renderer#139]
Forge: 14.23.4.2739 (latest today)
-OS: Windows10
-no other mods
-first run
-using MultiMC
Crash log: https://privatebin.net/?50101f6e12995263#vqBRWu6Soj9epzg1yIHbcuPlbPrgIS39vDuP0PYpKcU=

**Comment by DethRaid** [comment]
Duplicate of #138
