### ISSUE TITLE
GUI Buttons Not Always Positioned or Scaled Correctly

### ISSUE THREAD

**Issue by operation283** [NovaMods/nova-renderer#14]
The positions of the buttons in the Nova window are not always positioned or scaled in the same way as in the Minecraft window.

**Steps to reproduce:**
1. Start Nova.
2. Change the sizes of the two windows.
3. Go to another screen (like options) and back.
4. The buttons should be strangely positioned and scaled.

**Comment by DethRaid** [comment]
We're probably not propagating the window resizing properly.

**Comment by Maximilian-Reuter** [comment]
no longer relevant since there has been a big rewrite

**Comment by DethRaid** [comment]
Did you test that this was fixed?
