### ISSUE TITLE
Crash 0.7.3

### ISSUE THREAD

**Issue by supersim3** [NovaMods/nova-renderer#141]
Game crashed after world load.
Crash log [pastebin](https://pastebin.com/bagGkE9Vurl)
Log [pastebin](https://pastebin.com/DJ6HELzB)
The instance was still running in the background after the crash
![screenshot 27](https://user-images.githubusercontent.com/7007591/42922574-d3773c0a-8b53-11e8-9055-a4258dd23d9a.png)

**Comment by Janrupf** [comment]
Ok, so, does this happen every time? Sometimes it crashes just randomly.
Anyway, that is one of these `InvalidMemoryAccess` errors, that needs some investigation.

**Comment by supersim3** [comment]
Every time, sometimes it lasts a bit longer but not more than 5 seconds after world load. I have 24 gig with 8 allocated to minecraft.
