### ISSUE TITLE
0.7.3 start crash

### ISSUE THREAD

**Issue by FluffyDiscord** [NovaMods/nova-renderer#142]
forge log, nova log is empty
[latest.log](https://github.com/NovaMods/nova-renderer/files/2211552/latest.log)
What am I missing ?

**Comment by Janrupf** [comment]
That is not a direct duplicate of #141, but releated. Also `InvalidMemoryAccess`, here at startup.

**Comment by FluffyDiscord** [comment]
maybe i need to state my setup. The code may work on some configuration while it may break on the other.
System: 
Ryzen 7 1700 @3.9GHz
2x A-DATA 2999MHz CL14
Windows 10 64bit
RX 470

**Comment by Janrupf** [comment]
That are known bugs or WIP's, but the crashes with invalid memory access are not supposed to happen at all. @ImperatorS79 Please create an issue for the ALT+Tab and Done thing. The rest is currently being worked on.
