### ISSUE TITLE
Switching window (alt-tab) close the game if a menu is displayed.

### ISSUE THREAD

**Issue by ImperatorS79** [NovaMods/nova-renderer#145]
Start a world, press "esc" and then try to go to another window with alt-tab.

**Comment by Janrupf** [comment]
Looks like a platform dependent issue, doesn't happen for me on Ubuntu Budgie 18.10

**Comment by DethRaid** [comment]
@ImperatorS79 What system (OS/GPU/CPU) are you on?

**Comment by ImperatorS79** [comment]
OS : Windows 10 64-bits
CPU : i5-6600K
GPU : AMD R9 390X
