### ISSUE TITLE
How to compile and run on Linux

### ISSUE THREAD

**Issue by SuicSoft** [NovaMods/nova-renderer#15]
The instructions in the wiki only have Windows compile instructing. Linux and Mac OS instructions need to be added.

I can't run Nova on Linux anyways since my laptop's drivers don't support OpenGL 4.5 on Linux but do on Windows 10

**Comment by dotModded** [comment]
Mdsitton is working on a build script.

**Comment by SuicSoft** [comment]
@dotModded Can I download the build script ?

**Comment by DethRaid** [comment]
You'd have to talk to @mdsitton about that. It'll be hard to download, though, because he hasn't written it yet

**Comment by SuicSoft** [comment]
Maybe we should replace the build script with a build system like CMake

**Comment by DethRaid** [comment]
Not a bad idea. One thing I want to do is move the entire project to gradle. First, though, I want to get the codebase stable and I'm some sort of working order. It would be amazing if a helpful, passionate developer would help out... Maybe write the build script they want so much...

**Comment by SuicSoft** [comment]
@DethRaid I've started working on a CMake script to build Nova.

Also does Nova support Minecraft 1.11 and why hasn't there been any commits in the past 2 months ?

**Comment by DethRaid** [comment]
Nova does not support 1.11 yet. Mcp doesn't have a thing for 1.11, and I want to get the code in a good place before switching to 1.11.

There haven't been any commits in two months because I've been working off my fork of nova. It seemed like a good idea at the time, but I've reconsidered. Gonna merge back in once I get the main menu rendering again (i've been refactoring the code in a big way and trying to remove a bunch of complexity)

**Comment by mdsitton** [comment]
I would like to make it known @SuicSoft originally I had suggested on discord to make a cmake script for building of everything but as Deth mentioned he wants to move everything to gradle iirc. Idk if he will be replacing the cmake build code in that move though.

**Comment by DethRaid** [comment]
I don't know either. Will have to research more into if gradle can handle dependencies that use CMake.

On the other hand, Java dependencies don't rely on a specific build system, and there is a way for CMake to deal with Java. That might be a better option.

I'd love to see a pull request that can replace nova.ps1 with CMake. Could be sweet.

**Comment by SuicSoft** [comment]
@DethRaid I've started working on CMake build system for this project. Currently the CMake script only download and extracts MCP

**Comment by SuicSoft** [comment]
@DethRaid Where is the applydiff.exe Linux / Mac version located in MCP ?

**Comment by DethRaid** [comment]
I'm 95% sure that applydiff.exe is the Windows port of patch, which should be installed by default

**Comment by VoyTechnology** [comment]
I would personally suggest https://bazel.build, but I'm biased.
Found it easier to understand than CMake with more sane (Python like) syntax BUILD files, and is very fast when repeatedly building.

Only issue is that we would need project specific build rules for applying the patches, and the output binary would have to be extracted out of the bazel-bin directory

**Comment by DethRaid** [comment]
Let's stick with CMake for the time being. There's enough churn in the project from what I'm doing, let's not introduce much more

**Comment by SuicSoft** [comment]
@DethRaid what is a  reliable way to check if MCP has already decompiled Minecraft

**Comment by DethRaid** [comment]
Maybe check the return code of the decompile command? idk

**Comment by SuicSoft** [comment]
@DethRaid Feel free to branch my cmake branch and finished it since i don't have much time. The CMakeLists is about 50% finished.

**Comment by DethRaid** [comment]
Linux script added in commit https://github.com/NovaMods/nova-renderer/commit/d77f0657cec8e663bd2887e05182960bd58d266a
