### ISSUE TITLE
Error in compiling rewritten Nova with Minecraft Adapter

### ISSUE THREAD

**Issue by joaoh1** [NovaMods/nova-renderer#159]
I'm trying to compile the Nova Renderer, specifically the Minecraft mod, so i figured out how to put together the adapter and the renderer, and i tried to compile it, but after that, it failed to compile in the beginning because mesh_store isn't a thing but it was in the CMakeList, so i changed that to mesh_allocator.
After that, my Windows with a GCC 7.3.0 failed to compile at 89%, because of something related with the filesystem library.
So, i switched to Linux, a Kubuntu with GCC 8.1.0, this time, at 94%, it threw up a lot of errors and finally failed to compile.

[Log of the Windows build](https://hastebin.com/beqegucuce.cs)
[Log of the Linux build](https://hastebin.com/dixapariwi.pl)

**Comment by Janrupf** [comment]
Well, there is nothing to compile. At the moment we are rewriting nova entirely.
The Minecraft Adapter hasn't been updated in a while and is completly incompatible with the rewrite or the master branch. It **could** be compatible with the vulkan branch, which still includes it. If you want to know more you can join our discord https://discord.gg/VGqtadw.
I'm closing this as it isn't really valid at the moment.
