### ISSUE TITLE
Uhmm is this supposed to happen? (0.7.3)

### ISSUE THREAD

**Issue by MrAlexEsisteGia** [NovaMods/nova-renderer#172]
I guess not..
https://streamable.com/c2hh3 (listen for sounds)

Gpu: rx 570
Cpu: i5 8600k
Windows 10 1809
Forge 2655

**Comment by DethRaid** [comment]
That's actually expected behavior for that version. You're lucky it even ran - for a lot of people, myself included, it would not run

We're rewriting everything for the next release so hopefully we'll at least have different bugs lol

But yeah that's the best Nova has ever worked for anyone
