### ISSUE TITLE
Can't run the project.

### ISSUE THREAD

**Issue by bakwas247** [NovaMods/nova-renderer#19]
![image](https://cloud.githubusercontent.com/assets/6785746/21964289/31832652-db41-11e6-9d43-d3d1d28e9a69.png)

Keep getting this error.

**Comment by DethRaid** [comment]
Did you run ./nova.ps1 -compile? Did you copy libstdc++6 into the jars/1.10/1.10-natives/ directory (directory name might be wrong, on mobile). Were there any errors when you compiled?

**Comment by DethRaid** [comment]
Do you still have this issue?

**Comment by bakwas247** [comment]
Sorry, I only just got notified of your reply. I did do all those steps,
and had no errors, but I shall attempt again from scratch and reply my
results.

**Comment by MiningPickaxe** [comment]
Hello, I have the same problem
`Exception in thread "Client thread" java.lang.UnsatisfiedLinkError: Unable to load library 'nova-renderer': Native library (win32-x86-64/nova-renderer.dll) not found in resource path`
I did `.\nova.ps1 -setup` and afterwards `.\nova.ps1 -build` imported the project into IntelliJ, set the working directory + java.library.path. Now after reading this I ran .\nova.ps1 -compile, but nothing really happend, no errors, nothing. And still can't launch it in IntelliJ. Already copied libstdc++6.dll into the directory.

**Comment by MiningPickaxe** [comment]
So, I was searching for nova-renderer.dll in the nova folder, seems like it was not generated. Couldn't find a file

**Comment by DethRaid** [comment]
The DLL should be automatically copied to the jars/versions/1.10/1.10-natives folder. Is it there?

If not, could you post the full output of `.\nova.ps1 -build`?

**Comment by MiningPickaxe** [comment]
Well, after rebooting my PC it compiled the dll for me and IntelliJ can find it. 
But still, can't get it to start. Crash log is here: https://pastebin.com/qhjK1AiD
The whole log can be found here: https://pastebin.com/AugEfMFF

**Comment by DethRaid** [comment]
How did you get Nova? Did you just clone the master branch?

**Comment by MiningPickaxe** [comment]
Yes, just cloned it

**Comment by Maximilian-Reuter** [comment]
Reopen if still exists with newest code
