### ISSUE TITLE
Player's view being redirected to a certain angle at a direction upon unpausing the game

### ISSUE THREAD

**Issue by some-username-here1** [NovaMods/nova-renderer#199]
Sometimes, it would be upward, other times it would be towards the horizon.

Tested using Forge v14.23.3.2655

- OS: Windows 8.1 Professional (64-bit)
- CPU: Intel Core i5-4590
- GPU: AMD Radeon RX 580 8GB

**Comment by Janrupf** [comment]
duplicate of #121
