### ISSUE TITLE
Linux script don't working

### ISSUE THREAD

**Issue by wascardev** [NovaMods/nova-renderer#20]
```
Injecting MCP into Minecraft...
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -r -U 3 ../../java/net/minecraft/client/gui/GuiButton.java "../../../../../Nova Renderer/src/main/java/net/minecraft/client/gui/GuiButton.java"
|--- ../../java/net/minecraft/client/gui/GuiButton.java	2016-09-15 21:37:58.632260000 -0700
|+++ "../../../../../Nova Renderer/src/main/java/net/minecraft/client/gui/GuiButton.java"	2016-08-25 20:17:56.815877600 -0700
--------------------------
```

**Comment by DethRaid** [comment]
Yeah, dealing with the patch files has been strangely difficult. It's only a semi-solved problem.

There's no official Linux build script yet. Issue #15 started to deal with it, but the guy who was writing the Linux build script never quite finished it.

It'd be awesome if you could dig into this issue and figure out how to use the existing patch files on Linux

**Comment by DethRaid** [comment]
Linux script added in commit https://github.com/NovaMods/nova-renderer/commit/d77f0657cec8e663bd2887e05182960bd58d266a
