### ISSUE TITLE
Error: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by PilLFIENd1** [NovaMods/nova-renderer#203]
So this just started happening today, deleted mouse tweaks mode and had this to say. Playing the pack Sky Factory 4.0.2, might be relavent or not, today also added "FTBLib-5.4.1.96.jar" and "FTBUtilities-5.4.0.94.jar" to the modpack folder.
in my inventory/extended inventory/ crafting table inventory i have no issues, i can reproduce it multiple times when i use a tinkers construct crafting table with flux storage containers.

with some trouble shooting with some admins it seems it might have to do with something with flux storage containers and tinkers work tables not liking it, as well as some other items (not sure which) and the items rendering in the crafting table? but it is confirmed that it involves tinkers crafting tables and flux storage.

"The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.UnsupportedOperationException: Cannot cast map to int"

reinstalled the newest version and got this

The game crashed whilst handlemouseclick() threw an exception when called from mousetweaks.
Error: java.lang.reflect.InvocationTargetException

[crash-2019-04-24_20.49.23-client.txt](https://github.com/NovaMods/nova-renderer/files/3112432/crash-2019-04-24_20.49.23-client.txt)

**Comment by McHox** [comment]
don't expect nova to be useable anytime soon

**Comment by Janrupf** [comment]
Wow, I wonder you could even run the game xD. However, the old versions are not supported anymore and we are in a middle of a rewrite, so issues about old versions are not accepted anymore.

**Comment by PilLFIENd1** [comment]
so its nova? and an older version?

**Comment by Janrupf** [comment]
Is nova even loaded? I couldn't find it in the log. And note that the current version of nova doesn't run on Minecraft, thats why there are no new releases

**Comment by Janrupf** [comment]
// Accidently reopened

**Comment by PilLFIENd1** [comment]
not sure what you mean lol, what is the issue with what exactly?

which version is the older one? not exactly sure what nova is, what it does, or if its being used or not

**Comment by Janrupf** [comment]
I don't exactly get what you mean with "not sure what nova is", because you opened an issue here...
What lead to you opening an issue here then?

**Comment by PilLFIENd1** [comment]
i may have posted in the wrong section?
maybe it should have been in  FTBTeam/FTB-Utilities

i was under the impression that this was a fourm/platform for coding devs and others about mods etc
i had to create an account and verify email to go about adressing the issue with the crash report and some config clashes and crashes, along the way of creating this post i may have put it in the wrong area, apologies if i did

**Comment by PilLFIENd1** [comment]
i was searching through the site looking for others who might of experienced the same issue before creating a new thread

**Comment by Janrupf** [comment]
Ok, well, this is definetly the wrong place for that. You should contact the mod author about it. I'm not sure which mod causes this, but try to contact the mousetweaks author. Create an issue here: https://github.com/YaLTeR/MouseTweaks

**Comment by PilLFIENd1** [comment]
sorry and cheers
