### ISSUE TITLE
Remove old nova-renderer versions

### ISSUE THREAD

**Issue by yagomont** [NovaMods/nova-renderer#206]
As it seems that development has been progressing on this mod, and it's been a year since the last release, it would be a good idea to rid of them. I don't believe the outdated files can be used to get any meaningful feedback anymore. Probably the only thing they are there for is to spam the issues page with issues pertaining only to them. Which, the usual response is "this is outdated, pls ignore."

I, of course, am going under the assumption that the provided releases are radically different than Nova Renderer as it is today. The contrary would be saying no actual progress was done.

**Comment by McHox** [comment]
i agree

**Comment by Janrupf** [comment]
We will talk about this internally, I personally agree with what you said.

**Comment by Janrupf** [comment]
Confirmed! Old releases will be deleted.
