### ISSUE TITLE
Cannot install on Linux

### ISSUE THREAD

**Issue by Utopanic** [NovaMods/nova-renderer#260]
Newbie alert!
I'd like to try out the Nova renderer, but i fail to  install it. I'm on Linux Mint, I've installed the lunar sdk(i checked that it was the right version), but I got stuck on this command "git submodule update --init --recursive"
Could you help me, please?

**Comment by cwfitzgerald** [comment]
So for the time being, unless you want to help develop nova, you can't really install it. We'll publish a easy to install mod once everything is finished, but we're still heavy on development and don't have anything to try at this point.

Thanks for the interest though!

**Comment by Utopanic** [comment]
Oh okay, I'll look forward to it. Do you have any idea on when the mod will be released?

**Comment by Strum355** [comment]
When its ready
