### ISSUE TITLE
Forge Gradlew instead of MCP?

### ISSUE THREAD

**Issue by acterhd** [NovaMods/nova-renderer#33]
Hello. I see that you using MCP. Why you does not using Forge Gradlew? Also, gradlew (and even SRG/CSV) have support for 1.10.2.

http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp/1.10.2/mcp-1.10.2-srg.zip
http://export.mcpbot.bspk.rs/#

**Comment by DethRaid** [comment]
This issue has come up before, and investigating Forge Gradle is definitely on the backlog. It hasn't happened yet due mostly to other such as rendering the game world having a higher priority.

**Comment by DethRaid** [comment]
A little historical context: We originally used Forge, however Forge had some issues loading the native code and it made Minecraft take a very long time to start up. We switched to MCP and the native code loading issues were fixed

**Comment by acterhd** [comment]
You may tried change Intelij to eclipse.

**Comment by DethRaid** [comment]
Maybe could have tried that but I definitely didn't want to use eclipse

**Comment by acterhd** [comment]
This render - this is what I dreamed of ... For it is ready to score on the version of Minecraft. It is a pity that the game is not yet functional. I planned to add my ray tracing (and PhantomGL for OpenGL 4.5). But to add my rendering to a product that is almost empty is pretty painful. If you want, you can consider my PhantomGL.

**Comment by DethRaid** [comment]
Update: a new member of the team is working on converting Nova to be built off of Forge, rather than raw MCP

**Comment by DethRaid** [comment]
This work has been completed
