### ISSUE TITLE
patch unexpectedly ends in middle of line

### ISSUE THREAD

**Issue by Haruki1** [NovaMods/nova-renderer#42]
patch unexpectedly ends in middle of line
patch: **** Only garbage was found in the patch input.
Full output: https://pastebin.com/YThNb39g

**Comment by Maximilian-Reuter** [comment]
should be fixed in the chunks branch

**Comment by DethRaid** [comment]
While this issue is fixed, it'll come up again the next time I update the patch file. Will definitely have to solve this for good

**Comment by Maximilian-Reuter** [comment]
as far as I understand the issue it was because powershell made the patch in uft16 by default which is fixed in the chunks branch so this should not be an issue anymore

**Comment by DethRaid** [comment]
Yeah, the patch file is correct. I don't think the PowerShell code is fixed, though

**Comment by tobiasschulz** [comment]
I committed changes to the powershell script but they are untested.

**Comment by DethRaid** [comment]
I must have missed that when I looked through your changes. We're hopefully good, then
