### ISSUE TITLE
macOS - MCP failed to decompile

### ISSUE THREAD

**Issue by Rayzr522** [NovaMods/nova-renderer#50]
I was intrigued by your project and wanted to give it a shot, see if I could get it to compile and run on my system. Instead, I got this: https://pastebin.com/FeWBWsMd

Now, it's not to say that I didn't expect any bumps along the road to getting this working, but it would appear that the MCP `decompile.sh` script failed to find the `1.10.2.json`, which makes no sense since I've used MCP before with no problems.

I manually checked, the file *is* there. Not sure what MCP's problem is. If you need any more information, just let me know. I'll be attempting to work this out myself.

**Side note:** I was looking through the docs for `patch` and it appears that when it prompts you for `File to patch: `, that's because it can't find the file it was supposed to patch. You probably already know this and it makes complete sense because MCP failed to decompile. Just a note though, in case you've never seen that prompt before.

**Comment by Maximilian-Reuter** [comment]
as far as I know, macos has no plans to support opengl 4.5 so even if you got the setuzo and build to complete you wouldn't be able to launch the game....

**Comment by DethRaid** [comment]
It fails to find the 1.10.json, not the 1.10.2.json. Nova currently only works with 1.10, not 1.10.2 or 1.10.1. That's the problem you're having.

But yeah, as Maximilian said, OSX only supports OpenGL 4.1. Nova uses 4.5. Thus, OSX is not a supported platform. Sorry. At one point someone else tried porting Nova to OSX and they had some issue with the sound not working.

**Comment by Rayzr522** [comment]
Alright, fair enough, I might try my hand at it. Thanks for pointing out that it's 1.10 not 1.10.2, I probably would've spent several hours of dissecting MCP's decompile scripts before realizing that.

Sorry to bother you with my stupid mistakes, I'd love to try and get this to work or at least build. I'm going to be making the switch over to Linux soon (probably Arch) so I'll have to try again then.
