### ISSUE TITLE
Error when launching.

### ISSUE THREAD

**Issue by jobensingh** [NovaMods/nova-renderer#51]
Hi, for some reason whenever I attempt to launch Nova via ./gradlew runNova , I get an error and it doesn't launch. I'm not sure if this is an issue of my screwing up, or an issue with nova.

Error, without stack trace, i can print if necessary:

`PS C:\Users\coolj\nova-renderer> ./gradlew runNova
:buildDll
Starting compilation of Nova...
Building with MinGWildDll
-- Using Win32 for window creation
-- GLM is a header only library, no need to build it. Set the option GLM_TEST_ENABLE with ON to build and run the test b
ench
Initial BUILD_X64=ON
Initial CMAKE_BUILD_TYPE=Debug
miniz build type: Debug
Building 64-bit
-- Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/coolj/nova-renderer/target/cpp
Generated build files
[ 33%] Built target glfw
[100%] Built target nova-renderer-obj
[100%] Built target nova-renderer
Compiled code
Nova compiled!
True
:compileJava
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\util\registry\RegistrySimple.java:42: error: cannot find symbol
            Minecraft.getMinecraft().getNovaRenderer().registerStaticModel((ResourceLocation) key, (IBakedModel) value);
                                                      ^
  symbol:   method registerStaticModel(ResourceLocation,IBakedModel)
  location: class NovaRenderer
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\Minecraft.java:414: error: method preInit in class NovaR
enderer cannot be applied to given types;
        nova.preInit();
            ^
  required: ModelManager
  found: no arguments
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
`

**Comment by DethRaid** [comment]
I haven't updated Nova's changes to the Minecraft source code in a while. That's what's causing those errors. Gimme a bit and I'll update it

**Comment by jobensingh** [comment]
Alright thanks.

**Comment by DethRaid** [comment]
Try pulling the chunks branch and setting Nova up again

**Comment by jobensingh** [comment]
I get a little farther this time, now it gives me a new error, heres everything it output when I ran the command.
`:buildDll
Starting compilation of Nova...
Building with MinGWildDll
-- The C compiler identification is GNU 7.1.0
-- The CXX compiler identification is GNU 7.1.0
-- Check for working C compiler: C:/Program Files (x86)/mingw-w64/i686-7.1.0-posix-dwarf-rt_v5-rev0/mingw32/bin/gcc.
-- Check for working C compiler: C:/Program Files (x86)/mingw-w64/i686-7.1.0-posix-dwarf-rt_v5-rev0/mingw32/bin/gcc.
-- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/mingw-w64/i686-7.1.0-posix-dwarf-rt_v5-rev0/mingw32/bin/g+
e
-- Check for working CXX compiler: C:/Program Files (x86)/mingw-w64/i686-7.1.0-posix-dwarf-rt_v5-rev0/mingw32/bin/g+
e -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: opengl32
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found Vulkan: C:/Windows/System32/vulkan-1.dll
-- Looking for dinput.h
-- Looking for dinput.h - found
-- Looking for xinput.h
-- Looking for xinput.h - found
-- Performing Test _GLFW_HAS_DEP
-- Performing Test _GLFW_HAS_DEP - Success
-- Performing Test _GLFW_HAS_ASLR
-- Performing Test _GLFW_HAS_ASLR - Success
-- Performing Test _GLFW_HAS_64ASLR
-- Performing Test _GLFW_HAS_64ASLR - Failed
-- Using Win32 for window creation
-- GLM is a header only library, no need to build it. Set the option GLM_TEST_ENABLE with ON to build and run the te
ench
Initial BUILD_X64=ON
Initial CMAKE_BUILD_TYPE=Debug
miniz build type: Debug
Building 64-bit
-- Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/coolj/nova-renderer/target/cpp
Generated build files
Scanning dependencies of target glfw
[  3%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/context.c.obj
[  6%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/init.c.obj
[  6%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/input.c.obj
[ 10%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/monitor.c.obj
[ 13%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/vulkan.c.obj
[ 13%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/window.c.obj
[ 16%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/win32_init.c.obj
[ 20%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/win32_joystick.c.obj
[ 20%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/win32_monitor.c.obj
[ 23%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/win32_time.c.obj
[ 26%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/win32_tls.c.obj
[ 26%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/win32_window.c.obj
[ 30%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/wgl_context.c.obj
[ 30%] Building C object 3rdparty/glfw/src/CMakeFiles/glfw.dir/egl_context.c.obj
[ 33%] Linking C static library libglfw3.a
[ 33%] Built target glfw
Scanning dependencies of target nova-renderer-obj
[ 36%] Building C object CMakeFiles/nova-renderer-obj.dir/3rdparty/glad/src/glad.c.obj
[ 40%] Building C object CMakeFiles/nova-renderer-obj.dir/3rdparty/miniz/miniz.c.obj
[ 40%] Building CXX object CMakeFiles/nova-renderer-obj.dir/render/nova_renderer.cpp.obj
[ 43%] Building CXX object CMakeFiles/nova-renderer-obj.dir/mc_interface/nova_facade.cpp.obj
[ 46%] Building CXX object CMakeFiles/nova-renderer-obj.dir/render/objects/textures/texture_manager.cpp.obj
[ 46%] Building CXX object CMakeFiles/nova-renderer-obj.dir/render/objects/uniform_buffers/uniform_buffer_store.cpp.
[ 50%] Building CXX object CMakeFiles/nova-renderer-obj.dir/input/InputHandler.cpp.obj
[ 53%] Building CXX object CMakeFiles/nova-renderer-obj.dir/render/objects/shaders/gl_shader_program.cpp.obj
[ 53%] Building CXX object CMakeFiles/nova-renderer-obj.dir/render/objects/gl_mesh.cpp.obj
[ 56%] Building CXX object CMakeFiles/nova-renderer-obj.dir/render/objects/textures/texture2D.cpp.obj
[ 60%] Building CXX object CMakeFiles/nova-renderer-obj.dir/render/windowing/glfw_gl_window.cpp.obj
[ 60%] Building CXX object CMakeFiles/nova-renderer-obj.dir/utils/utils.cpp.obj
[ 63%] Building CXX object CMakeFiles/nova-renderer-obj.dir/data_loading/settings.cpp.obj
[ 66%] Building CXX object CMakeFiles/nova-renderer-obj.dir/data_loading/loaders/shader_loading.cpp.obj
[ 66%] Building CXX object CMakeFiles/nova-renderer-obj.dir/data_loading/loaders/loader_utils.cpp.obj
[ 70%] Building CXX object CMakeFiles/nova-renderer-obj.dir/render/objects/shaders/shaderpack.cpp.obj
[ 73%] Building CXX object CMakeFiles/nova-renderer-obj.dir/geometry_cache/mesh_store.cpp.obj
[ 73%] Building CXX object CMakeFiles/nova-renderer-obj.dir/data_loading/physics/AABB.cpp.obj
[ 76%] Building CXX object CMakeFiles/nova-renderer-obj.dir/geometry_cache/mesh_definition.cpp.obj
[ 80%] Building CXX object CMakeFiles/nova-renderer-obj.dir/render/objects/shaders/geometry_filter.cpp.obj
[ 80%] Building CXX object CMakeFiles/nova-renderer-obj.dir/render/objects/uniform_buffers/uniform_buffers_definitio
pp.obj
[ 83%] Building CXX object CMakeFiles/nova-renderer-obj.dir/geometry_cache/builders/chunk_builder.cpp.obj
[ 86%] Building CXX object CMakeFiles/nova-renderer-obj.dir/mc_interface/mc_objects.cpp.obj
[ 86%] Building CXX object CMakeFiles/nova-renderer-obj.dir/render/objects/framebuffer.cpp.obj
[ 90%] Building CXX object CMakeFiles/nova-renderer-obj.dir/render/objects/camera.cpp.obj
[ 90%] Building CXX object CMakeFiles/nova-renderer-obj.dir/utils/io.cpp.obj
[ 93%] Building CXX object CMakeFiles/nova-renderer-obj.dir/data_loading/loaders/geometry_filter_loading.cpp.obj
[ 96%] Building CXX object CMakeFiles/nova-renderer-obj.dir/data_loading/loaders/shader_source_structs.cpp.obj
[ 96%] Building CXX object CMakeFiles/nova-renderer-obj.dir/geometry_cache/builders/vertex_format_decoder.cpp.obj
[100%] Building CXX object CMakeFiles/nova-renderer-obj.dir/3rdparty/renderdocapi/RenderDocManager.cpp.obj
C:\Users\coolj\nova-renderer\src\main\cpp\3rdparty\renderdocapi\RenderDocManager.cpp:28:0: warning: "ELPP_THREAD_SAF
edefined
 #define ELPP_THREAD_SAFE

<command-line>:0:0: note: this is the location of the previous definition
[100%] Built target nova-renderer-obj
Scanning dependencies of target nova-renderer
[100%] Linking CXX shared library nova-renderer.dll
        1 file(s) copied.
[100%] Built target nova-renderer
Compiled code
Nova compiled!
True
:compileJava
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\renderer\BlockModelShapes.java:3: error: cannot find
bol
import com.continuum.nova.NovaConstants;
                         ^
  symbol:   class NovaConstants
  location: package com.continuum.nova
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\renderer\BlockModelShapes.java:6: error: cannot find
bol
import com.continuum.nova.chunks.BlockModelSerializer;
                                ^
  symbol:   class BlockModelSerializer
  location: package com.continuum.nova.chunks
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\gui\GuiSlot.java:16: error: cannot find symbol
import static com.continuum.nova.NovaConstants.WHITE_TEXTURE_GUI_LOCATION;
                                ^
  symbol:   class NovaConstants
  location: package com.continuum.nova
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\gui\GuiSlot.java:16: error: static import only from
ses and interfaces
import static com.continuum.nova.NovaConstants.WHITE_TEXTURE_GUI_LOCATION;
^
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\renderer\BlockModelShapes.java:118: error: cannot fi
ymbol
        BlockModelSerializer serializer = nova.getModelSerializer();
        ^
  symbol:   class BlockModelSerializer
  location: class BlockModelShapes
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\renderer\BlockModelShapes.java:118: error: cannot fi
ymbol
        BlockModelSerializer serializer = nova.getModelSerializer();
                                              ^
  symbol:   method getModelSerializer()
  location: variable nova of type NovaRenderer
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\renderer\BlockModelShapes.java:128: error: cannot fi
ymbol
            serializer.serialize(NovaConstants.MODEL_FILE_NAME);
                                 ^
  symbol:   variable NovaConstants
  location: class BlockModelShapes
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\renderer\BlockModelShapes.java:129: error: cannot fi
ymbol
            NovaNative.INSTANCE.load_block_state_models(NovaConstants.MODEL_FILE_NAME);
                                                        ^
  symbol:   variable NovaConstants
  location: class BlockModelShapes
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\gui\GuiSlot.java:270: error: cannot find symbol
            NovaDraw.draw(WHITE_TEXTURE_GUI_LOCATION, indices, shade);
                          ^
  symbol:   variable WHITE_TEXTURE_GUI_LOCATION
  location: class GuiSlot
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\gui\GuiSlot.java:284: error: cannot find symbol
            NovaDraw.draw(WHITE_TEXTURE_GUI_LOCATION, indices, shade);
                          ^
  symbol:   variable WHITE_TEXTURE_GUI_LOCATION
  location: class GuiSlot
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\gui\GuiSlot.java:310: error: cannot find symbol
                NovaDraw.draw(WHITE_TEXTURE_GUI_LOCATION, indices, scrollbarBackground);
                              ^
  symbol:   variable WHITE_TEXTURE_GUI_LOCATION
  location: class GuiSlot
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\gui\GuiSlot.java:324: error: cannot find symbol
                NovaDraw.draw(WHITE_TEXTURE_GUI_LOCATION, indices, scrollbarShade);
                              ^
  symbol:   variable WHITE_TEXTURE_GUI_LOCATION
  location: class GuiSlot
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\gui\GuiSlot.java:340: error: cannot find symbol
                NovaDraw.draw(WHITE_TEXTURE_GUI_LOCATION, indices, scrollbar);
                              ^
  symbol:   variable WHITE_TEXTURE_GUI_LOCATION
  location: class GuiSlot
C:\Users\coolj\nova-renderer\src\main\java\net\minecraft\client\gui\GuiSlot.java:460: error: cannot find symbol
        ResourceLocation whiteTextureLocation = WHITE_TEXTURE_GUI_LOCATION;
                                                ^
  symbol:   variable WHITE_TEXTURE_GUI_LOCATION
  location: class GuiSlot
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
14 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 41.057 secs`

**Comment by DethRaid** [comment]
Are you sure that MCP setup correctly? Check that the solder src/main/java/net isn't empty

**Comment by jobensingh** [comment]
It is not empty

**Comment by jobensingh** [comment]
Anything else that could be wrong?

**Comment by DethRaid** [comment]
Based on the errors, it almost looks like you don't have the latest version of the source code. I would say to try pulling again, and maybe that will work for you, but maybe I've made enough changes to the MC code that the patch file is out of date and you'll just get more errors...

This brings up something I've been thinking about lately. I cannot support branches other than `master`. I just can't. I make too many changes in a given day, then the patch file and the Nova source code get out of sync, then there's a ton of problems.

If you absolutely need to run Nova now, use `master`. It should all work as-is. But honestly, Nova is still so early in development that I'm surprised anytime anyone gets it working. The best way to run Nova is to wait until Nova is further along in development and has more features and is more stable.
