### ISSUE TITLE
Punches Purchasing problem 

### ISSUE THREAD

**Issue by DefinitlyEvil** [NovaMods/nova-renderer#55]
I got error code like this: 
BC5Z6GNSHGCBKP4Y24D9 
And MY MONEY IS GONE!

**Comment by DefinitlyEvil** [comment]
I bought a tier-3 PULCHRA package and I it gave me an a error, then I found my money GONE!

**Comment by DethRaid** [comment]
Please email support@continuum.graphics about this issue.

**Comment by DefinitlyEvil** [comment]
Hi again, I sent the mail and please respond ASAP, I rly wanna try it out (the res pack) ;D

**Comment by DefinitlyEvil** [comment]
sry to reply here again, i sent a access request on Google Drive. plz approve it ;) have train tomorrow i gonna be quick

**Comment by DethRaid** [comment]
Please stop using this issue to talk about purchasing problems. This github repo is for nova and nova alone. For issues with purchasing, email support@continuum.graphics. There's actually a separate person watching that email address, I don't handle that. Continuuing to post here will have no impact on resolving your issue
