### ISSUE TITLE
About multi-gpu PC

### ISSUE THREAD

**Issue by DefinitlyEvil** [NovaMods/nova-renderer#56]
Is it possible to power up the game with NVIDIA GPUs by using SLI technology? I got double Titan X (Maxwell) but it can only use one. :(

**Comment by DethRaid** [comment]
Sli and crossfire support is planned but it'll probably be a long time before it's implemented. Therrs a lot to get to first

**Comment by DefinitlyEvil** [comment]
Yep, if SLI supported, Minecraft can have a cinematic look rather than a simple pixel game. ;)

**Comment by DethRaid** [comment]
Nova likely won't use SLI or Crossfire for multi-GPI support, but may handle that itself. See issue #161 for more discussion

Closing this issue since I won't be doing SLI or Crossfire

**Comment by DefinitlyEvil** [comment]
glad to hear some updates! :D

**Comment by DefinitlyEvil** [comment]
glad to hear some updates! :D
