### ISSUE TITLE
Fails when injecting Nova into Minecraft

### ISSUE THREAD

**Issue by Flandyn** [NovaMods/nova-renderer#57]
Log:
PS E:\> git clone -b chunks https://github.com/NovaMods/nova-renderer.git
Cloning into 'nova-renderer'...
remote: Counting objects: 6402, done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 6402 (delta 5), reused 28 (delta 5), pack-reused 6341
Receiving objects: 100% (6402/6402), 11.93 MiB | 1.47 MiB/s, done.
Resolving deltas: 100% (3471/3471), done.
PS E:\> Set-ExecutionPolicy Restricted -Scope CurrentUser -Force
PS E:\> Set-ExecutionPolicy Unrestricted -Scope Process -Force
PS E:\> Set-Location nova-renderer
PS E:\nova-renderer> .\nova.ps1 -setup
Downloading MCP...

    Directory: E:\nova-renderer

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       09/08/2017     13:22                mcp
== MCP 9.30 (data: 9.31, client: 1.10, server: 1.10) ==
"scalac" is not found on the PATH.  Scala files will not be recompiled
 found ff, ff patches, srgs, name csvs, doc csvs, param csvs, astyle, astyle config, rg, ss
Looking in C:\Users\1234567890\AppData\Roaming\.minecraft\versions for mc installs... OK
Copying assets... OK
Parsing JSON file... OK
Looking for minecraft main jar... Not found
Copying minecraft main jar... OK
> Checking libraries...
        Copying library jinput... OK
        Copying library lwjgl-platform... OK
        Copying library icu4j-core-mojang... OK
        Copying library httpcore... OK
        Copying library log4j-api... OK
        Copying library commons-lang3... OK
        Copying library jna... OK
        Copying library libraryjavasound... OK
        Copying library jopt-simple... OK
        Copying library guava... OK
        Copying library oshi-core... OK
        Copying library httpclient... OK
        Copying library commons-compress... OK
        Copying library fastutil... OK
        Copying library platform... OK
        Copying library codecjorbis... OK
        Copying library soundsystem... OK
        Copying library librarylwjglopenal... OK
        Copying library lwjgl_util... OK
        Copying library commons-codec... OK
        Copying library jutils... OK
        Copying library commons-logging... OK
        Copying library lwjgl... OK
        Copying library commons-io... OK
        Copying library realms... OK
        Copying library authlib... OK
        Copying library gson... OK
        Copying library netty... OK
        Copying library codecwav... OK
        Copying library jinput-platform... OK
        Copying library log4j-core... OK
        Copying library netty-all... OK
> Checking Natives...
        Extracting native lwjgl.dll... OK
        Extracting native OpenAL32.dll... OK
        Extracting native jinput-dx8_64.dll... OK
        Extracting native jinput-wintab.dll... OK
        Extracting native jinput-dx8.dll... OK
        Extracting native jinput-raw.dll... OK
        Extracting native OpenAL64.dll... OK
        Extracting native jinput-raw_64.dll... OK
        Extracting native lwjgl64.dll... OK
> Copying jsr305-3.0.1.jar to Libraries
> Copying jsr305-3.0.1-sources.jar to Libraries
== Decompiling client using fernflower ==
> Creating SRGs
> Applying SpecialSource
> Applying MCInjector
> Creating renamed srg
> Filtering classes
> Decompiling
> Unpacking jar
> Copying sources
> Generating package-info files
> Applying fernflower fixes
> Applying patches
> Cleaning comments
- Done in 77.54 seconds
== Reformating client ==
> Cleaning sources
> Replacing OpenGL constants
> Reformating sources
- Done in 9.25 seconds
== Updating client ==
> Adding javadoc
> Renaming sources
- Done in 6.97 seconds
!! Missing server jar file. Aborting !!
== Recompiling client ==
> Cleaning bin
> Recompiling
- Done in 16.02 seconds
> Generating client md5s
Press any key to continue . . .
Injecting Nova into Minecraft...
patching file .gitignore
Assertion failed: hunk, file patch-2.5.4/patch.c, line 343

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by DethRaid** [comment]
What commit of what branch are you on?

**Comment by willi123yao** [comment]
Oh its that applydiff bug that always happen for me. Try using patch from mingw

**Comment by Flandyn** [comment]
@willi123yao What patch from MinGW?

**Comment by willi123yao** [comment]
@Flandyn https://sourceforge.net/projects/mingw/files/MSYS/Extension/patch/patch-2.6.1-1/patch-2.6.1-1-msys-1.0.13-bin.tar.lzma/download 

There you can find the patch binaries for MinGW.

**Comment by Flandyn** [comment]
@willi123yao This is what i get now:


patching file .gitignore
can't find file to patch at input line 16
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/minecraft/block/Block.java b/minecraft/block/Block.java
|index 25c6330..da115a5 100644
|--- a/minecraft/block/Block.java
|+++ b/minecraft/block/Block.java
--------------------------
File to patch:

**Comment by Flandyn** [comment]
This issue has been fixed
