### ISSUE TITLE
Include directories hard coded to authors own windows enviroment.

### ISSUE THREAD

**Issue by mdsitton** [NovaMods/nova-renderer#6]
I could fix the CMakeLists.txt and do a pull request but you'd need to change some stuff on your end. I have access to Linux, and OSX(though osx is a bit pointless if your only going to be targeting opengl 4.3? with its max of 4.1)

Also i'd like to contribute somewhat, but there isnt really any decent way to talk about the project maybe setup a https://gitter.im/ chat?

**Comment by mdsitton** [comment]
I'm working on fixing this and will do a pull request.

**Comment by VoyTechnology** [comment]
I agree. Gitter would be very useful. Asking questions with Github issues can be awkward

**Comment by phase** [comment]
IRC is a possibility. esper or http://spi.gt/ are good.

**Comment by DethRaid** [comment]
We have a discord at https://discordapp.com/invite/014ux6siiDogn9FLz

**Comment by mdsitton** [comment]
Ok i've submitted my pull request #9.

**Comment by DethRaid** [comment]
Pull request that fixed this is merged, so this issue should be solved.
