### ISSUE TITLE
Missing Gradle tasks

### ISSUE THREAD

**Issue by Flandyn** [NovaMods/nova-renderer#65]
When running the command "gradle fatjar createJars" this error appears:

FAILURE: Build failed with an exception.

* What went wrong:
Task 'fatjar' not found in root project 'Nova Renderer'. Some candidates are: 'jar'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output.

BUILD FAILED in 15s
New-NovaCode : Gradle invocation failed, aborting
At G:\nova-renderer\nova.ps1:327 char:5
       New-NovaCode -buildEnvironment $buildEnvironment
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-NovaCode

False

**Comment by DethRaid** [comment]
Fixed in # 7a56b48

Note that I've made the gradle script fully able to build and run Nova. The PowerShell script is now deprecated.

Build Nova: `./gradlew build buildDll`
Run Nova: `./gradlew runNova`
