### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by Flandyn** [NovaMods/nova-renderer#67]
Build fails when running ".\nova.ps1 -build -buildEnvironment msvc"

Done Building Project "G:\nova\nova-renderer\target\cpp-msvc\3rdparty\optional\test_type_traits.vcxproj" (default targe
ts) -- FAILED.

Done Building Project "G:\nova\nova-renderer\target\cpp-msvc\3rdparty\optional\test_type_traits.vcxproj.metaproj" (defa
ult targets) -- FAILED.

Done Building Project "G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default targets) -- FAILED.

Done Building Project "G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default targets) -- FAILED.

Build FAILED.

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\json\test\json_unit.vcxproj.metaproj" (default target) (28) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\json\test\json_unit.vcxproj" (default target) (29) ->
(ClCompile target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\algorithm(1782): warn
ing C4244: 'argument': conversion from '_Diff' to 'Catch::RandomNumberGenerator::result_type', possible loss of data [G
:\nova\nova-renderer\target\cpp-msvc\3rdparty\json\test\json_unit.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\3rdparty\json\test\src\unit-class_parser.cpp(103): warning C4566: character repres
ented by universal-character-name '\uFF01' cannot be represented in the current code page (1252) [G:\nova\nova-renderer
\target\cpp-msvc\3rdparty\json\test\json_unit.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\3rdparty\json\test\src\unit-concepts.cpp(76): warning C4018: '<=': signed/unsigned
 mismatch [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\json\test\json_unit.vcxproj]
  g:\nova\nova-renderer\src\main\cpp\3rdparty\json\test\src\catch.hpp(1366): warning C4018: '<=': signed/unsigned misma
tch [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\json\test\json_unit.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\3rdparty\json\test\src\unit-constructor1.cpp(1282): warning C4996: 'nlohmann::basi
c_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator>::basic_json': was declared depreca
ted [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\json\test\json_unit.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\3rdparty\json\test\src\unit-constructor1.cpp(1290): warning C4996: 'nlohmann::basi
c_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator>::basic_json': was declared depreca
ted [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\json\test\json_unit.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\3rdparty\json\test\src\unit-constructor1.cpp(1308): warning C4996: 'nlohmann::basi
c_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator>::basic_json': was declared depreca
ted [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\json\test\json_unit.vcxproj]

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\nova-renderer.vcxproj.metaproj" (default target) (32) ->
"G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj.metaproj" (default target) (33) ->
"G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj" (default target) (34) ->
  G:\nova\nova-renderer\src\main\cpp\3rdparty\glad\src\glad.c(751): warning C4090: 'function': different 'const' qualif
iers [G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\mc_interface\nova_facade.cpp(145): warning C4267: '+=': conversion from 'size_t' t
o 'int', possible loss of data [G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\mc_interface\nova_facade.cpp(146): warning C4267: '+=': conversion from 'size_t' t
o 'int', possible loss of data [G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\mc_interface\nova_facade.cpp(154): warning C4267: '+=': conversion from 'size_t' t
o 'int', possible loss of data [G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\mc_interface\nova_facade.cpp(160): warning C4267: '+=': conversion from 'size_t' t
o 'int', possible loss of data [G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\mc_interface\nova_facade.cpp(153): warning C4996: 'strcpy': This function or varia
ble may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online hel
p for details. [G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\mc_interface\nova_facade.cpp(159): warning C4996: 'strcpy': This function or varia
ble may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online hel
p for details. [G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\data_loading\loaders\shader_loading.cpp(223): warning C4101: 'e': unreferenced loc
al variable [G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\render\objects\framebuffer.cpp(39): warning C4267: 'argument': conversion from 'si
ze_t' to 'GLsizei', possible loss of data [G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\render\objects\framebuffer.cpp(77): warning C4267: 'argument': conversion from 'si
ze_t' to 'GLsizei', possible loss of data [G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj]
  g:\nova\nova-renderer\src\main\cpp\render\objects\gl_mesh.cpp(69): warning C4715: 'nova::gl_mesh::translate_usage': n
ot all control paths return a value [G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared\minwindef.h(130): warning C4005: 'APIENTRY': macro
 redefinition [G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\3rdparty\renderdocapi\RenderDocManager.cpp(28): warning C4005: 'ELPP_THREAD_SAFE':
 macro redefinition [G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj]

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\nova-renderer.vcxproj.metaproj" (default target) (32) ->
"G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj.metaproj" (default target) (33) ->
"G:\nova\nova-renderer\target\cpp-msvc\nova-renderer-obj.vcxproj" (default target) (34) ->
(Lib target) ->
  mesh_definition.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so i
t will not be used by any link operation that consumes this library [G:\nova\nova-renderer\target\cpp-msvc\nova-rendere
r-obj.vcxproj]

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj.metaproj" (default target) (36) ->
"G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj" (default target) (37) ->
(ClCompile target) ->
  G:\nova\nova-renderer\src\main\cpp\3rdparty\glad\src\glad.c(751): warning C4090: 'function': different 'const' qualif
iers [G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\mc_interface\nova_facade.cpp(145): warning C4267: '+=': conversion from 'size_t' t
o 'int', possible loss of data [G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\mc_interface\nova_facade.cpp(146): warning C4267: '+=': conversion from 'size_t' t
o 'int', possible loss of data [G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\mc_interface\nova_facade.cpp(154): warning C4267: '+=': conversion from 'size_t' t
o 'int', possible loss of data [G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\mc_interface\nova_facade.cpp(160): warning C4267: '+=': conversion from 'size_t' t
o 'int', possible loss of data [G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\mc_interface\nova_facade.cpp(153): warning C4996: 'strcpy': This function or varia
ble may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online hel
p for details. [G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\mc_interface\nova_facade.cpp(159): warning C4996: 'strcpy': This function or varia
ble may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online hel
p for details. [G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\data_loading\loaders\shader_loading.cpp(223): warning C4101: 'e': unreferenced loc
al variable [G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj]
  g:\nova\nova-renderer\src\main\cpp\render\objects\gl_mesh.cpp(69): warning C4715: 'nova::gl_mesh::translate_usage': n
ot all control paths return a value [G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\render\objects\framebuffer.cpp(39): warning C4267: 'argument': conversion from 'si
ze_t' to 'GLsizei', possible loss of data [G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\render\objects\framebuffer.cpp(77): warning C4267: 'argument': conversion from 'si
ze_t' to 'GLsizei', possible loss of data [G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared\minwindef.h(130): warning C4005: 'APIENTRY': macro
 redefinition [G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj]

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\example1.vcxproj.metaproj" (default target) (4) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\example1.vcxproj" (default target) (5) ->
(ClCompile target) ->
  cl : Command line error D8021: invalid numeric argument '/Wextra' [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\min
iz\example1.vcxproj]

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\example2.vcxproj.metaproj" (default target) (6) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\example2.vcxproj" (default target) (7) ->
  cl : Command line error D8021: invalid numeric argument '/Wextra' [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\min
iz\example2.vcxproj]

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\example3.vcxproj.metaproj" (default target) (8) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\example3.vcxproj" (default target) (9) ->
  cl : Command line error D8021: invalid numeric argument '/Wextra' [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\min
iz\example3.vcxproj]

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\example4.vcxproj.metaproj" (default target) (10) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\example4.vcxproj" (default target) (11) ->
  cl : Command line error D8021: invalid numeric argument '/Wextra' [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\min
iz\example4.vcxproj]

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\example5.vcxproj.metaproj" (default target) (12) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\example5.vcxproj" (default target) (13) ->
  cl : Command line error D8021: invalid numeric argument '/Wextra' [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\min
iz\example5.vcxproj]

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\example6.vcxproj.metaproj" (default target) (14) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\example6.vcxproj" (default target) (15) ->
  cl : Command line error D8021: invalid numeric argument '/Wextra' [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\min
iz\example6.vcxproj]

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\miniz_tester.vcxproj.metaproj" (default target) (30) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\miniz\miniz_tester.vcxproj" (default target) (31) ->
  cl : Command line error D8021: invalid numeric argument '/Wextra' [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\min
iz\miniz_tester.vcxproj]

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj.metaproj" (default target) (36) ->
"G:\nova\nova-renderer\target\cpp-msvc\nova-test.vcxproj" (default target) (37) ->
  G:\nova\nova-renderer\src\main\cpp\test\geometry_cache\builders\chunk_builder_test.cpp(10): fatal error C1083: Cannot
 open include file: '../../../geometry_cache/builders/chunk_builder.h': No such file or directory [G:\nova\nova-rendere
r\target\cpp-msvc\nova-test.vcxproj]
  G:\nova\nova-renderer\src\main\cpp\test\geometry_cache\builders\vertex_format_decoder_test.cpp(9): fatal error C1083:
 Cannot open include file: '../../../geometry_cache/builders/vertex_format_decoder.h': No such file or directory [G:\no
va\nova-renderer\target\cpp-msvc\nova-test.vcxproj]

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\optional\test_optional.vcxproj.metaproj" (default target) (38) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\optional\test_optional.vcxproj" (default target) (39) ->
  cl : Command line error D8021: invalid numeric argument '/Wextra' [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\opt
ional\test_optional.vcxproj]

"G:\nova\nova-renderer\target\cpp-msvc\renderer.sln" (default target) (1) ->
"G:\nova\nova-renderer\target\cpp-msvc\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\optional\test_type_traits.vcxproj.metaproj" (default target) (40) ->
"G:\nova\nova-renderer\target\cpp-msvc\3rdparty\optional\test_type_traits.vcxproj" (default target) (41) ->
  cl : Command line error D8021: invalid numeric argument '/Wextra' [G:\nova\nova-renderer\target\cpp-msvc\3rdparty\opt
ional\test_type_traits.vcxproj]

    33 Warning(s)
    11 Error(s)

Time Elapsed 00:02:30.13
:compileJava
G:\nova\nova-renderer\src\main\java\net\minecraft\block\Block.java:1400: error: cannot find symbol
        Minecraft.getMinecraft().getNovaRenderer().registerBlock(id, block_);
                                                  ^
  symbol:   method registerBlock(int,Block)
  location: class NovaRenderer
G:\nova\nova-renderer\src\main\java\net\minecraft\client\renderer\BlockModelShapes.java:118: error: cannot find symbol
        BlockModelSerializer serializer = nova.getModelSerializer();
                                              ^
  symbol:   method getModelSerializer()
  location: variable nova of type NovaRenderer
G:\nova\nova-renderer\src\main\java\net\minecraft\client\renderer\BlockModelShapes.java:128: error: cannot find symbol
            serializer.serialize(NovaConstants.MODEL_FILE_NAME);
                                              ^
  symbol:   variable MODEL_FILE_NAME
  location: class NovaConstants
G:\nova\nova-renderer\src\main\java\net\minecraft\client\renderer\BlockModelShapes.java:129: error: cannot find symbol
            NovaNative.INSTANCE.load_block_state_models(NovaConstants.MODEL_FILE_NAME);
                                                                     ^
  symbol:   variable MODEL_FILE_NAME
  location: class NovaConstants
G:\nova\nova-renderer\src\main\java\net\minecraft\client\Minecraft.java:414: error: method preInit in class NovaRenderer
 cannot be applied to given types;
        nova.preInit(modelManager);
            ^
  required: no arguments
  found: ModelManager
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.133 secs
New-NovaCode : Gradle invocation failed, aborting
At G:\nova\nova-renderer\nova.ps1:327 char:5
     New-NovaCode -buildEnvironment $buildEnvironment
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-NovaCode

False






When running "./gradlew build buildDll" the build also fails:


PS G:\nova\nova-renderer> ./gradlew build buildDll
:compileJava
G:\nova\nova-renderer\src\main\java\net\minecraft\block\Block.java:1400: error: cannot find symbol
        Minecraft.getMinecraft().getNovaRenderer().registerBlock(id, block_);
                                                  ^
  symbol:   method registerBlock(int,Block)
  location: class NovaRenderer
G:\nova\nova-renderer\src\main\java\net\minecraft\client\renderer\BlockModelShapes.java:118: error: cannot find symbol
        BlockModelSerializer serializer = nova.getModelSerializer();
                                              ^
  symbol:   method getModelSerializer()
  location: variable nova of type NovaRenderer
G:\nova\nova-renderer\src\main\java\net\minecraft\client\renderer\BlockModelShapes.java:128: error: cannot find symbol
            serializer.serialize(NovaConstants.MODEL_FILE_NAME);
                                              ^
  symbol:   variable MODEL_FILE_NAME
  location: class NovaConstants
G:\nova\nova-renderer\src\main\java\net\minecraft\client\renderer\BlockModelShapes.java:129: error: cannot find symbol
            NovaNative.INSTANCE.load_block_state_models(NovaConstants.MODEL_FILE_NAME);
                                                                     ^
  symbol:   variable MODEL_FILE_NAME
  location: class NovaConstants
G:\nova\nova-renderer\src\main\java\net\minecraft\client\Minecraft.java:414: error: method preInit in class NovaRenderer
 cannot be applied to given types;
        nova.preInit(modelManager);
            ^
  required: no arguments
  found: ModelManager
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.114 secs

**Comment by DethRaid** [comment]
The patch file is out of date. You're trying to build the chunks branch, aren't you?

I really need to set up a thing to generate the patch file every commit

**Comment by DethRaid** [comment]
This should be fixed now, and I added a gradle task to build the patch file so hopefully I'll start seeing this problem less and less
