### ISSUE TITLE
Gradle claims that no main class is defined for task ':runNova'

### ISSUE THREAD

**Issue by Rayzr522** [NovaMods/nova-renderer#69]
Alright, I bypassed the `buildDll` step by making it just `echo` some text to the console (to deal with #68), and then I built the native code via `nova.sh`. However, I'm getting this problem now:

```
$ ./gradlew runNova 
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:assemble UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build UP-TO-DATE
:buildDll
IGNORING BUILDDLL TASK
:runNova FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runNova'.
> No main class specified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.976 secs
```

The task is described in the `build.gradle` file like this:

```
task runNova(type: JavaExec, dependsOn: ['buildDll', 'build']) << {
    dependsOn buildDll
    classpath = sourceSets.main.runtimeClasspath
    main = 'Start'
    jvmArgs = ["-Djava.library.path=versions/1.10/1.10-natives"]
    workingDir = "jars"
}
```

The error doesn't make much sense, considering that the the main class is set *right there.* Any ideas?

**EDIT:** The only change I made to the `build.gradle` file is this:
```diff
diff --git a/build.gradle b/build.gradle
index 84e2619..b01829a 100644
--- a/build.gradle
+++ b/build.gradle
@@ -29,7 +29,8 @@ jar {
 }
 
 task buildDll(type: Exec) {
-    commandLine 'powershell', '-file', 'nova.ps1', '-build', '-nativeOnly'
+    // commandLine 'powershell', '-file', 'nova.ps1', '-build', '-nativeOnly'
+    commandLine 'echo', 'IGNORING BUILDDLL TASK'
 }
 
 task runNova(type: JavaExec, dependsOn: ['buildDll', 'build']) << {
```

**Comment by DethRaid** [comment]
There's a possibility that MCP didn't unpack properly so gradle can't find the main class

**Comment by Rayzr522** [comment]
I mean, I checked for the class file, and it *was* there. And if MCP didn't unpack properly, wouldn't it have failed to build?

**Comment by DethRaid** [comment]
I don't even know any more.

I'm getting CI set up so there will be pre-build binaries available and people who want to use Nova won't have to use the apparently horribly unstable scripts that seem to break on every machine but mine

**Comment by Rayzr522** [comment]
Welcome to open-source development, my friend.

**Comment by DethRaid** [comment]
We're just committed some changes to the build script. Could you test again and see if Nova works for you?
