### ISSUE TITLE
Setup errors

### ISSUE THREAD

**Issue by Flandyn** [NovaMods/nova-renderer#71]
Running ".\gradlew.bat setup" in PowerShell fails:

PS G:\nova-renderer> .\gradlew.bat setup
Configuring for MinGW
:verifyEnvironment
CMake found!
:downloadMcp
Download http://www.modcoderpack.com/files/mcp931.zip
:decompileMcp
== MCP 9.30 (data: 9.31, client: 1.10, server: 1.10) ==
"scalac" is not found on the PATH.  Scala files will not be recompiled
 found ff, ff patches, srgs, name csvs, doc csvs, param csvs, astyle, astyle config, rg, ss
FATAL ERROR
Traceback (most recent call last):
  File "runtime/decompile.py", line 61, in decompile
    commands.checkupdates()
  File "G:\nova-renderer\runtime\commands.py", line 1058, in checkupdates
    md5_file = md5(fh.read()).hexdigest()
IOError: [Errno 13] Permission denied
:decompileMcp FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'G:\nova-renderer\setup.gradle' line: 87

* What went wrong:
Execution failed for task ':decompileMcp'.
> Process 'command './runtime/bin/python/python_mcp'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.753 secs

I ran "python runtime/decompile.py" myself and removed that task and now i get this error:

Configuring for MinGW
:verifyEnvironment
CMake found!
:downloadMcp
Download http://www.modcoderpack.com/files/mcp931.zip
:decompileMcp
:copyMcCode
:copyMcAssets
:copyMcPack
:applyPatch FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'G:\nova-renderer\setup.gradle' line: 106

* What went wrong:
Execution failed for task ':applyPatch'.
> Cannot call TaskOutputs.upToDateWhen(Closure) on task ':applyPatch' after task has started execution. Check the config
uration of task ':applyPatch' as you may have misused '<<' at task declaration.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.588 secs

**Comment by DethRaid** [comment]
I've gotten that one about python a few times. Not sure the exact cause yet. 

When I work on Nova tomorrow I'll be working on that second error you got

**Comment by Flandyn** [comment]
That error is fixed, but now i get this error:

:applyPatch FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'E:\nova-renderer\setup.gradle' line: 142

* What went wrong:
org.gradle.api.GradleScriptException (no error message)
> A problem occurred starting process 'command 'E:\nova-renderer/mcp/runtime/bin/applydiff.exe''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 16.307 secs

**Comment by DethRaid** [comment]
I've gotten that error a lot as well. Try running `./gradlew setup --info --stacktrace` and see if that tells you anything interesting

**Comment by Flandyn** [comment]
Fixed
