### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by VoyTechnology** [NovaMods/nova-renderer#8]
Currently there are no unit tests for the project. Setting some kind of a Continuous Integration would be useful. It will also make sure that everything builds and there are no problems after merging. I recommend https://travis-ci.org

**Comment by DethRaid** [comment]
I've tried setting up gtest but couldn't get it to build properly on my machine. I can work on this more this weekend. Unit testing GL code is always fun.

**Comment by mdsitton** [comment]
I've always liked how dolphin does it. They have this image differ that compares a before and after image of several sources. I came aross something similar recently but cant for the life of me remember what it was from...

**Comment by mdsitton** [comment]
But basically we could render something with the minecraft rendering, then another thing with this backend. and compare the results by diffing the image. This would easily show if anything is different.

**Comment by DethRaid** [comment]
Basic GUI stuff is nearing completion, then I'll get testing set up

**Comment by DethRaid** [comment]
Finally working on testing. Whoop whoop!

**Comment by DethRaid** [comment]
Writing tests for the problematic sections of the code. Will continue writing tests as more code gets written. Check out https://github.com/NovaMods/nova-renderer/tree/master/src/main/cpp/test for some current tests
