### ISSUE TITLE
Is it possible for MC 1.7.10?

### ISSUE THREAD

**Issue by TataTawa** [NovaMods/nova-renderer#83]
nova-render is awesome and great!! Is there any chance for 1.7.10?

**Comment by DethRaid** [comment]
The exact Minecraft versions that Nova supports are not set in stone. I plan on surveying the community or grabbing statistics from something like Optifine and figuring out what the most populate version of MC are, then making Nova work on those. There's definitely a chance of Nova coming to 1.7.10

**Comment by TataTawa** [comment]
I have found that there's a site showing the amount of mods for every minecraft version:

[https://bot.notenoughmods.com](url)

This team is using web spyder to grab data back and forth. The data is updated frequently.
We can clearly see that 1.7.10 overpower any other version twice and more. Many mods are actively maintained at this time.
Actually, 1.7.10 is one of the most lively version of mc, mainly because the big code change from 1.7 to 1.8 makes lots of modders go away. Fastcraft makes the game more smooth, and this vital mod is only in 1.7.10. Several important mod is left behind after 1.7.10. Version 1.8 to 1.11 is also short-lifed.
🙋These information may help you.

  | List name | Mod count | Last updated
-- | -- | -- | --
  | 1.13 | 1 | Sun, 23 Sep 2018 23:49:40
  | 1.12.2 | 248 | Tue, 30 Oct 2018 22:35:24
  | 1.12.1 | 201 | Fri, 26 Oct 2018 02:47:07
  | 1.12 | 232 | Fri, 26 Oct 2018 02:47:05
  | 1.11.2 | 259 | Tue, 23 Oct 2018 15:45:32
  | 1.11 | 148 | Sun, 23 Sep 2018 23:55:54
  | 1.10.2 | 390 | Tue, 23 Oct 2018 15:45:38
  | 1.10 | 168 | Sun, 23 Sep 2018 23:55:42
  | 1.9.4 | 260 | Tue, 23 Oct 2018 15:45:44
  | 1.9 | 239 | Sun, 23 Sep 2018 23:55:56
  | 1.8.9 | 375 | Tue, 23 Oct 2018 15:45:42
  | 1.8.8 | 141 | Tue, 23 Oct 2018 15:45:40
  | 1.8.7 | 3 | Sun, 23 Sep 2018 23:56:08
  | 1.8.6 | 3 | Sun, 23 Sep 2018 23:56:06
  | 1.8.5 | 3 | Sun, 23 Sep 2018 23:56:04
  | 1.8.4 | 4 | Sun, 23 Sep 2018 23:56:02
  | 1.8.3 | 6 | Sun, 23 Sep 2018 23:56:14
  | 1.8.2 | 3 | Sun, 23 Sep 2018 23:56:12
  | 1.8.1 | 8 | Sun, 23 Sep 2018 23:56:10
  | 1.8 | 282 | Tue, 23 Oct 2018 15:45:36
  | 1.7.10 | 1216 | Tue, 23 Oct 2018 15:45:34
  | 1.7.9 | 8 | Sun, 23 Sep 2018 23:41:41
  | 1.7.7 | 6 | Sun, 23 Sep 2018 23:47:50
  | 1.7.5 | 7 | Sun, 23 Sep 2018 23:47:54
  | 1.7.4 | 9 | Sun, 23 Sep 2018 23:47:58
  | 1.7.2 | 480 | Sun, 23 Sep 2018 23:55:14
  | 1.6.4 | 674 | Sun, 23 Sep 2018 23:39:31
  | 1.6.2 | 409 | Sun, 23 Sep 2018 23:39:29
  | 1.6.1 | 63 | Fri, 23 Jan 2015 23:30:53
  | 1.5.2 | 381 | Wed, 27 Sep 2017 16:05:19
  | 1.5.1 | 255 | Sat, 12 Mar 2016 13:19:21
  | 1.4.7 | 281 | Wed, 27 Sep 2017 16:45:50
  | 1.4.5 | 126 | Fri, 23 Jan 2015 23:30:09

**Comment by yagomont** [comment]
That's going to be a challenge. Most mods already break Nova, now imagine something that changes deeply how the game works like FastCraft, Optifine & FoamFix to name a few. Nova might be the optimization we have been looking for all this time.

By the time this is mature, 1.7.10 will be pretty much dead(-er). I believe it would be better if Nova didn't have to ever adapt to the old code base. Keeping it on 1.12-> and further will just make development more streamlined, and hopefully easier.
