### ISSUE TITLE
Gradle cannot start applydiff

### ISSUE THREAD

**Issue by Flandyn** [NovaMods/nova-renderer#85]
G:\nova-renderer>gradlew setup
Configuring for MSVC 64-bit
:verifyEnvironment
CMake found!
Could not find GCC. If you want to use GCC to compile Nova, please install it to your PATH and try again
:downloadMcp
Download http://www.modcoderpack.com/files/mcp931.zip
:decompileMcp
== MCP 9.30 (data: 9.31, client: 1.10, server: 1.10) ==
"scalac" is not found on the PATH.  Scala files will not be recompiled
# found ff, ff patches, srgs, name csvs, doc csvs, param csvs, astyle, astyle config, rg, ss
!! client already decompiled. Run cleanup before decompiling again !!

:copyMcCode UP-TO-DATE
:copyMcAssets UP-TO-DATE
:copyMcPack UP-TO-DATE
:applyPatch FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'G:\nova-renderer\setup.gradle' line: 145

* What went wrong:
org.gradle.api.GradleScriptException (no error message)
> A problem occurred starting process 'command 'G:\nova-renderer/mcp/runtime/bin/applydiff.exe''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.274 secs

**Comment by Plasticable** [comment]
Try to copy folder `net` from `nova-renderer\mcp\src\minecraft` to `nova-renderer\src\main\java`
