### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by FireMasterK** [NovaMods/nova-renderer#89]
Hi, i am getting a few compile errors, could you please help me?
[Log](https://hastebin.com/vurifovugu.tex)

**Comment by DethRaid** [comment]
The patch file didn't apply.

Try deleting the file `mc_from_git` if it's in the root directory of where you cloned Nova and running `./gradlew applyPatch`. You should either get a success or an error message of some sort

**Comment by FireMasterK** [comment]
New error: https://hastebin.com/ayohokaruh.tex

**Comment by DethRaid** [comment]
We're just committed some changes to the build script. Could you test again and see if Nova works for you?

**Comment by FireMasterK** [comment]
Sure I will try later today

**Comment by FireMasterK** [comment]
https://hastebin.com/epecisisoq.vbs

**Comment by FireMasterK** [comment]
New error

**Comment by DethRaid** [comment]
`Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)`

You need to install the Vulkan SDK

**Comment by FireMasterK** [comment]
https://hastebin.com/wibecetiyo.tex
New error

**Comment by DethRaid** [comment]
Hmm... I guess MSVC has a different set of errors on `std::tuple` than GCC. That's annoying.

I just pushed a commit that should fix that error. Pull and try again

**Comment by FireMasterK** [comment]
https://hastebin.com/efejofulih.tex
New error

**Comment by DethRaid** [comment]
Sorry, I completely lost track of this issue

Looks like it's been long enough that hastebin deleted the log you posted. Could you post the log again?

**Comment by FireMasterK** [comment]
Sorry for late reply, you started releasing releases on github. That will do. Thanks!
