### ISSUE TITLE
Ability to show compiled shader code to the developer?

### ISSUE THREAD

**Issue by jcm2606** [NovaMods/nova-renderer#90]
Or at least a close-enough representation of roughly what it should look like, if you can't get exact compiled code from the driver.

**Comment by DethRaid** [comment]
Here's what I'm thinking:

- Nova will create a folder, `debug`, where the compiled shader code will be output
- `debug/shaders` will have your shader files after all includes have been processed
- `debug/shaders/glsl450` will have the shaders after they've been transpiled to GLSL 450 with the GLSL Vulkan extension
    - If you've written your shaders in GLSL for Vulkan, this folder will just have your shaders as is
- `debug/shaders/spirv` will have the SPIR-V code that your shaders are compiled to
- `debug/shaders/compiled` will have the compiled shaders (if I can get them)

**Comment by DethRaid** [comment]
Nova outputs the compiled SPIR-V to the shaderpack directory
