### ISSUE TITLE
Allow shader packs to manually bind uniforms.

### ISSUE THREAD

**Issue by jcm2606** [NovaMods/nova-renderer#91]
Currently Optifine automatically binds uniforms while parsing the shader, which severely constricts the format that a dev may choose to use for their shader. If they write the code in a certain way, Optifine won't know what to do, and the shader just breaks without any warning, often with particularly... interesting... results.

If Nova could provide a way for devs to create manual bindings, that would solve a lot of headaches related to how restrictive Optifine is to shader packs.

As for specifically how they work, even something as simple as a section in the JSON file(s) for a given pack that maps Nova's provided data to a given uniform variable in the shader source would work.

**Comment by DethRaid** [comment]
The plan for Nova is to use uniform buffers to get uniforms to the GPU. Uniforms are thus represented uniquely as an offset in that buffer. I could see a system where you add a comment or something to your uniform which specifies its offset, then Nova's shader compiler will make sure the data is laid out correctly

Example:

```glsl
uniform vec3 lightDirection;     // offset: 9
```

**Comment by DethRaid** [comment]
Nova's materials allow binding arbitrary resources to arbitrary uniforms
