### ISSUE TITLE
Error in Compiling Nova

### ISSUE THREAD

**Issue by joaoh1** [NovaMods/nova-renderer#92]
Well, i tried to compile Nova, but i got the same errors as #89, i tried to follow the advices from it, nothing happened.
[Logs](https://hastebin.com/comacivira.tex)

**Comment by joaoh1** [comment]
Found solution at #86, but now i'm stuck at this:
[More logs](https://hastebin.com/kabakoqayi.sql)

**Comment by DethRaid** [comment]
We're just committed some changes to the build script. Could you test again and see if Nova works for you?

**Comment by DethRaid** [comment]
@joaoh1 Does the new build script work for you?

**Comment by joaoh1** [comment]
The current vulkan branch compiles for me now, closing this.
