### ISSUE TITLE
Even more errors

### ISSUE THREAD

**Issue by Flandyn** [NovaMods/nova-renderer#99]
This is what I get when running `gradlew build buildDll`: 
https://pastebin.com/RdXDdCt4

And this is what I get after copying `mcp\src\minecraft\net` to `src\main\java\net`: https://pastebin.com/Ji9Vb06n

This is what I get after copying `mcp\src\minecraft\mcp` to `src\main\java\mcp` and adding `compile group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.0'` to build.gradle as specified in #86 : https://pastebin.com/bknv5Xt4

And when trying to manually apply patch, applydiff.exe just remains running for hours, doing absolutely nothing.

**Comment by DethRaid** [comment]
We're just committed some changes to the build script. Could you test again and see if Nova works for you?
